## Управление доступом с помощью ключевого слова `pub`

Мы исправили ошибки связанные с распределением рукописи. Но остались сбои с использованием рукописи (функции не используются):

```text
warning: function is never used: `connect`, #[warn(dead_code)] on by default
src/client.rs:1:1
  |
1 | fn connect() {
  | ^

warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/mod.rs:1:1
  |
1 | fn connect() {
  | ^

warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/server.rs:1:1
  |
1 | fn connect() {
  | ^
```

Почему имеют место эти ошибки? Библиотеки существуют для того, чтобы ими пользовались пользователи. Поэтому важно, чтобы сбои с доступом к возможностям языка были решены.

Для того, чтобы понять почему существуют такие ошибки, и как важно их устранить,
попробуем воспользоваться возможностями рукописи извне. Для этого создадим выполняемое
дело в этой же папке. Создадим файл *src/main.rs*, который содержит:

<span class="filename">Filename: src/main.rs</span>

```rust,ignore
extern crate communicator;

fn main() {
    communicator::client::connect();
}
```

Мы сейчас использовали приказ `extern crate` для того чтобы использовать возможности
библиотеки `communicator` в нашей новой программе. Cargo использует файл *src/main.rs*,
как точку доступа для двоичной программы, в то время, как *src/lib.rs* используется
для библиотеки. Такое создание рукописи довольно-таки обычно. Большинство рукописи
находится в библиотеках, а двоичный файл просто использует эту библиотеку. Итогом
такой архитектуры является возможность другим программам также использовать возможности
библиотеки.

Со стороны сторонней рукописи все что находится в библиотеке имеет пространство имён
`communicator` (имя библиотеки) верхнего уровня. Всё остальное, это подчиненные разделы.

Также, обратите внимание, что когда мы используем внешние библиотеки с внутренними вложениями,
приказ `extern crate` начинает искать разделы с верхнего уровня.

В нашей программе двоичный файл вызывает библиотечную функцию `connect` из
раздела `client`. Но при сборке этой рукописи получим сообщении об ошибке:

```text
error: module `client` is private
 --> src/main.rs:4:5
  |
4 |     communicator::client::connect();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Это сообщение говорит нам о том, что раздел `client` закрытое.
Т.к. рукопись в разделе закрытая по умолчанию и не используется внутри библиотеки - на это надо обратить внимание, т.к. это явная ошибка в согласовании рукописи.

После определения функции `client::connect`, как доступной (`pub`), не только сообщение об ошибке исчезнет, но и пропадёт сообщение о том, что рукопись не используется.
Создания доступной рукописи в Ржавчине даёт возможность её использования вне библиотеки.
Когда какая-либо рукопись помечается как `pub`, сборщик больше не сообщает об неиспользованной рукописи, если даже она в действительности не используется.

### Сделать функции доступными

Для того, чтобы сделать что-либо доступным извне, необходимо добавить ключевое слово `pub` в начало объявления переменной или способа рукописи. Для исправления ошибки, мы добавим этот определитель доступа перед определением имени раздела:

<span class="filename">Filename: src/lib.rs</span>

```rust,ignore
pub mod client;

mod network;
```

Ключевое слово `pub` перед `mod`. Сборка. Сообщение об ошибке:

```text
error: function `connect` is private
 --> src/main.rs:4:5
  |
4 |     communicator::client::connect();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Сделаем исправления в определении функции в файле *src/client.rs*:

<span class="filename">Filename: src/client.rs</span>

```rust
pub fn connect() {
}
```

Снова выполним `cargo clean && cargo build`:

```text
warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/mod.rs:1:1
  |
1 | fn connect() {
  | ^

warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/server.rs:1:1
  |
1 | fn connect() {
  | ^
```

Рукопись собралась и предостережения о функции `client::connect` уже нет!

Вам решать, что делать с неиспользованной рукописью, то ли открыть к ней доступ, то ли
удалить.

В данном случае мы хотим, чтобы эти функции были доступны. Поэтому добавим `pub`
там, где это необходимо:

<span class="filename">Filename: src/network/mod.rs</span>

```rust,ignore
pub fn connect() {
}

mod server;
```

Соберем и рассмотрим ошибки:

```text
warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/mod.rs:1:1
  |
1 | pub fn connect() {
  | ^

warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/server.rs:1:1
  |
1 | fn connect() {
  | ^
```

Для того, чтобы открытые функции раздела были доступны, само раздел должно быть доступно:

<span class="filename">Filename: src/lib.rs</span>

```rust,ignore
pub mod client;

pub mod network;
```

Новые сообщения сборщика:

```text
warning: function is never used: `connect`, #[warn(dead_code)] on by default
 --> src/network/server.rs:1:1
  |
1 | fn connect() {
  | ^
```

Надеюсь, что теперь исправить последний недочёт программы вам не составит труда.

### Правила доступа


1. Если переменная открытая, она должна быть открытый и все родительские разделы тоже.
2. Если переменная закрытая, она может быть доступна только из родительского раздела и из любых подчиненных разделов.

### Примеры

Создадим новое дело библиотеки secret 7-5 *src/lib.rs*:

<span class="filename">Filename: src/lib.rs</span>

```rust,ignore
mod outermost {
    pub fn middle_function() {}

    fn middle_secret_function() {}

    mod inside {
        pub fn inner_function() {}

        fn secret_function() {}
    }
}

fn try_me() {
    outermost::middle_function();
    outermost::middle_secret_function();
    outermost::inside::inner_function();
    outermost::inside::secret_function();
}
```

<span class="caption">Рукопись 7-5: Примеры открытых и закрытый функций с ошибками</span>

Перед сборкой рукописи, попробуйте догадаться, где будет ошибка. Убедитесь в этом
с помощью сборки. Исправьте ошибки в рукописи!

#### Рассмотрим ошибки

Функция `try_me` находится на верхнем уровне раздела нашего дела. Раздел
`outermost` закрытое, но к его функциям может быть доступ, т.к. раздел верхнего
уровня.

Вызов остальных двух функций вызовет ошибку, т.к. не применяются правила видимости.
Пожалуйста, исправьте ошибку!

#### Исправление ошибок

Пожалуйста, попытайтесь по	проводить опыты с доступом к функциям  и посмотрите
на описания ошибок!

Далее, мы поговорим об использовании ключевого слова `use`.
